### ISSUE TITLE
[1.19.2-0.3.0] Furnace stops working 1 tick too early

### ISSUE THREAD

**Issue by Kiryonn** [InZan123/Unloaded-Activity-Fabric#7] opened 2023-05-12 12:21 UTC
you put 1 log in the furnace, burn it with 2 stick and don't get charcoal. The reason is that furnaces stops working 1 tick too early

**Comment by InZan123** [comment] 2023-05-12 20:33
I tried to reproduce it but everything seems to work as intended. When I put in 1 log and 2 sticks and let it cook normally, I get a charcoal and when I do it again but running the command "/time add 1d" while its cooking I still get a charcoal. 

Can you clairify what the issue is? And do you have any other mods installed?

**Comment by Kiryonn** [comment] 2023-05-12 21:43
maybe it's another incompatibility with lithium ?

**Comment by Kiryonn** [comment] 2023-05-12 21:47
i've packed my current modpack using curesforge export. maybe it will help you ?
[1.19.2 - Fabric combat tech.zip](https://github.com/InZan123/Unloaded-Activity-Fabric/files/11467966/1.19.2.-.Fabric.combat.tech.zip)

**Comment by InZan123** [comment] 2023-05-13 12:27
i was able to reproduce the issue with the modpack and two sticks wouldn't be enough for 1 log. Since your modpack also had lithium there was the issue mentioned [here](https://github.com/InZan123/Unloaded-Activity-Fabric/issues/3). Doing the fix in the comments fixed the issue and also fixed the issue you were having. I'm not exactly sure why that issue would cause the items to not have enough fuel to cook though.

But this issue will be fixed in the next update which I'll hopefully get done soon. In the meantime you could try the temporary solution in the comments of the other issue I linked.

**Comment by Kiryonn** [comment] 2023-05-13 13:25
thanks

**Closed** 2023-05-13 14:41 UTC
